# Generated by Django 5.2.4 on 2025-07-29 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_order_options_alter_product_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
